root -l -b runAnalyzer.C\(\"signal\",\"250\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"350\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"350\",\"200\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"200\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"300\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"200\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"300\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"400\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"200\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"300\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"400\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"500\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"100\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"200\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"300\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"400\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"500\",\"bj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"250\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"350\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"350\",\"200\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"200\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"450\",\"300\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"200\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"300\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"550\",\"400\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"200\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"300\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"400\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"650\",\"500\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"100\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"200\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"300\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"400\",\"jj\"\) -q
root -l -b runAnalyzer.C\(\"signal\",\"750\",\"500\",\"jj\"\) -q
